// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ConsoleOnBoot","status":true,"description":"Shows the developer console on boot.","parameters":{"Console Width":"800","Console Height":"300","Console X-Position":"0","Console Y-Position":"0","Game Window X-Offset":"150","Game Window Y-Offset":"0","Autofocus":"true"}},
{"name":"Test","status":true,"description":"","parameters":{}}
];
